
function playback(opts) {
  var records = [];

  function record(key, data) {
    records.push({key: key, data: data});
  }

  function playback() {
    var lines = [
        'library angular.core.service.playback_data;',
        '',
        'import "dart:json" as json;',
        '',
        '// Auto-generated by record-playback',
        '',
        'Map<String, String> playbackData = {'
    ];

    records.forEach(function(r) {
      lines.push('  \'' + r.key + '\': json.parse(r\'' + r.data + '\'),')
    });

    lines.push('};');

    return lines.join('\n');
  }

  return {
    record: record,
    playback: playback
  }
}

module.exports = {
  playback: playback
};
