import "angular_spec.dart" as t1;
// import "io/expression_extractor_spec.dart" as t2;
// import "io/source_metadata_extractor_spec.dart" as t3;
// import "io/template_cache_generator_spec.dart" as t4;
import "touch/ng_swipe_spec.dart" as t5;
import "routing/ng_bind_route_spec.dart" as t6;
import "routing/ng_view_spec.dart" as t7;
import "routing/routing_spec.dart" as t8;
import "introspection_spec.dart" as t9;
import "directive/ng_pluralize_spec.dart" as t10;
import "directive/ng_events_spec.dart" as t11;
import "directive/ng_style_spec.dart" as t12;
import "directive/ng_bind_spec.dart" as t13;
import "directive/ng_switch_spec.dart" as t14;
import "directive/ng_repeat_spec.dart" as t15;
import "directive/ng_model_validators_spec.dart" as t16;
import "directive/ng_cloak_spec.dart" as t17;
import "directive/ng_if_spec.dart" as t18;
import "directive/ng_model_datelike_spec.dart" as t19;
import "directive/ng_model_spec.dart" as t20;
import "directive/ng_bind_template_spec.dart" as t21;
import "directive/ng_template_spec.dart" as t22;
import "directive/ng_bind_html_spec.dart" as t23;
import "directive/ng_class_spec.dart" as t24;
import "directive/ng_model_select_spec.dart" as t25;
import "directive/ng_non_bindable_spec.dart" as t26;
import "directive/ng_src_boolean_spec.dart" as t27;
import "directive/ng_form_spec.dart" as t28;
import "directive/a_href_spec.dart" as t29;
import "directive/ng_base_css_spec.dart" as t30;
import "directive/ng_show_hide_spec.dart" as t31;
import "directive/ng_include_spec.dart" as t32;
import "formatter/lowercase_spec.dart" as t33;
import "formatter/date_spec.dart" as t34;
import "formatter/currency_spec.dart" as t35;
import "formatter/filter_spec.dart" as t36;
import "formatter/uppercase_spec.dart" as t37;
import "formatter/order_by_spec.dart" as t38;
import "formatter/number_spec.dart" as t39;
import "formatter/limit_to_spec.dart" as t40;
import "formatter/arrayify_spec.dart" as t41;
import "formatter/json_spec.dart" as t42;
import "cache/cache_spec.dart" as t43;
import "cache/js_cache_register_spec.dart" as t44;
import "cache/cache_register_spec.dart" as t45;
import "mock/http_backend_spec.dart" as t46;
import "mock/zone_spec.dart" as t47;
import "mock/test_bed_spec.dart" as t48;
import "playback/playback_http_spec.dart" as t49;
import "change_detection/watch_group_spec.dart" as t50;
import "change_detection/context_locals_spec.dart" as t51;
import "change_detection/dirty_checking_change_detector_spec.dart" as t52;
import "core/pending_async_spec.dart" as t53;
import "core/annotation_src_spec.dart" as t54;
import "core/templateurl_spec.dart" as t55;
import "core/zone_spec.dart" as t56;
import "core/interpolate_spec.dart" as t57;
import "core/core_directive_spec.dart" as t58;
import "core/scope_spec.dart" as t59;
import "core/component_css_loader_spec.dart" as t60;
import "core/parser/parser_spec.dart" as t61;
import "core/parser/generated_getter_setter_spec.dart" as t62;
import "core/parser/lexer_spec.dart" as t63;
import "utils_spec.dart" as t64;
import "bootstrap_spec.dart" as t65;
import "core_dom/selector_spec.dart" as t66;
import "core_dom/cookies_spec.dart" as t67;
import "core_dom/view_spec.dart" as t68;
import "core_dom/default_platform_shim_spec.dart" as t69;
import "core_dom/element_binder_builder_spec.dart" as t70;
import "core_dom/ng_element_spec.dart" as t71;
import "core_dom/web_components_spec.dart" as t72;
import "core_dom/shimming_view_cache_spec.dart" as t73;
import "core_dom/directive_injector_spec.dart" as t74;
import "core_dom/compiler_spec.dart" as t75;
import "core_dom/resource_url_resolver_spec.dart" as t76;
import "core_dom/light_dom_spec.dart" as t77;
import "core_dom/ng_animate_spec.dart" as t78;
import "core_dom/shadow_boundary_spec.dart" as t79;
import "core_dom/css_shim_spec.dart" as t80;
import "core_dom/event_handler_spec.dart" as t81;
import "core_dom/mustache_spec.dart" as t82;
import "core_dom/platform_js_based_shim_spec.dart" as t83;
import "core_dom/directive_spec.dart" as t84;
import "core_dom/node_cursor_spec.dart" as t85;
import "core_dom/http_spec.dart" as t86;
import "core_dom/view_cache_spec.dart" as t87;
import "animate/css_animation_spec.dart" as t88;
import "animate/ng_animate_spec.dart" as t89;
import "animate/animation_loop_spec.dart" as t90;
import "animate/animation_optimizer_spec.dart" as t91;
import "animate/css_animate_spec.dart" as t92;

import "_specs.dart" as specs;

main() {
  specs.main();
  // t2.main();
  // t3.main();
  // t4.main();

  t75.main();

  // t1.main();
  // t5.main();
  // t6.main();
  // t7.main();
  // t8.main();
  // t9.main();
  // t10.main();
  // t11.main();
  // t12.main();
  // t13.main();
  // t14.main();
  // t15.main();
  // t16.main();
  // t17.main();
  // t18.main();
  // t19.main();
  // t20.main();
  // t21.main();
  // t22.main();
  // t23.main();
  // t24.main();
  // t25.main();
  // t26.main();
  // t27.main();
  // t28.main();
  // t29.main();
  // t30.main();
  // t31.main();
  // t32.main();
  // t33.main();
  // t34.main();
  // t35.main();
  // t36.main();
  // t37.main();
  // t38.main();
  // t39.main();
  // t40.main();
  // t41.main();
  // t42.main();
  // t43.main();
  // t44.main();
  // t45.main();
  // t46.main();
  // t47.main();
  // t48.main();
  // t49.main();
  // t50.main();
  // t51.main();
  // t52.main();
  // t53.main();
  // t54.main();
  // t55.main();
  // t56.main();
  // t57.main();
  // t58.main();
  // t59.main();
  // t60.main();
  // t61.main();
  // t62.main();
  // t63.main();
  // t64.main();
  // t65.main();
  // t66.main();
  // t67.main();
  // t68.main();
  // t69.main();
  // t70.main();
  // t71.main();
  // t72.main();
  // t73.main();
  // t74.main();
  // t75.main();
  // t76.main();
  // t77.main();
  // t78.main();
  // t79.main();
  // t80.main();
  // t81.main();
  // t82.main();
  // t83.main();
  // t84.main();
  // t85.main();
  // t86.main();
  // t87.main();
  // t88.main();
  // t89.main();
  // t90.main();
  // t91.main();
  // t92.main();
}
